# Generated by Django 4.2.3 on 2023-08-05 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_status', models.CharField(choices=[], max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('socials', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('password', models.CharField(max_length=255)),
                ('avatar', models.ImageField(upload_to='avatars/')),
                ('description', models.TextField()),
                ('seller_address', models.CharField(max_length=255)),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_goods', models.JSONField()),
                ('price', models.FloatField()),
                ('images', models.ImageField(upload_to='goods/')),
                ('namegoods', models.CharField(max_length=255)),
                ('goods_id', models.IntegerField()),
                ('afrom', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projjjapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projjjapi.good')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projjjapi.user')),
            ],
        ),
    ]
