# Generated by Django 4.2.3 on 2023-08-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projjjapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rating',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='seller_status',
            field=models.CharField(blank=True, choices=[], max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='socials',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
