# Generated by Django 4.2.3 on 2023-08-06 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projjjapi', '0002_remove_user_rating_alter_user_avatar_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
