# Generated by Django 4.2.3 on 2023-08-06 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projjjapi', '0003_rename_user_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='seller_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
