# Generated by Django 4.2.3 on 2023-08-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projjjapi', '0004_alter_users_description_alter_users_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
