# Generated by Django 4.2.3 on 2023-08-16 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projjjapi', '0006_users_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Good',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
